# 📄 .github/actions/build-images/action.yml
name: "Build KFP Images"
description: "Build all KFP Docker images"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build images
      shell: bash
      run: ./.github/resources/scripts/build-images.sh
