name: "Deploy KFP"
description: "Deploy KFP to the Kubernetes cluster"

inputs:
  proxy:
    description: "If KFP should be deployed with proxy configuration"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Deploy KFP
      shell: bash
      run: |
        if [ "${{ inputs.proxy }}" = "true" ]; then
          ./.github/resources/scripts/deploy-kfp.sh --proxy
        else
          ./.github/resources/scripts/deploy-kfp.sh
        fi 