name: "Deploy KFP"
description: "Deploy KFP to the Kubernetes cluster"

inputs:
  proxy:
    description: "If KFP should be deployed with proxy configuration"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Deploy KFP
      shell: bash
      run: |
        if [ "${{ inputs.proxy }}" = "true" ]; then
          ./.github/resources/scripts/deploy-kfp.sh --proxy
        else
          ./.github/resources/scripts/deploy-kfp.sh
        fi

        # Check if all pods are running
        echo "Waiting for KFP pods to be ready..."
        kubectl wait --for=condition=ready pod --all -n kubeflow --timeout=300s || true
        
        # List all resources in the kubeflow namespace
        echo "Resources in kubeflow namespace:"
        kubectl get all -n kubeflow 