name: "Set up KinD Cluster"
description: "Create a Kubernetes in Docker (KinD) cluster"

inputs:
  k8s_version:
    description: "The Kubernetes version to use for the Kind cluster"
    required: true
  proxy:
    description: "If Squid proxy should be deployed"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Create k8s Kind Cluster
      uses: container-tools/kind-action@v2
      with:
        cluster_name: kfp
        kubectl_version: ${{ inputs.k8s_version }}
        version: v0.25.0
        node_image: kindest/node:${{ inputs.k8s_version }}

    - name: Deploy Squid
      id: deploy-squid
      if: ${{ (inputs.proxy == 'true' )}}
      shell: bash
      run: ./.github/resources/squid/deploy-squid.sh
