apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../../../manifests/kustomize/env/platform-agnostic

images:
- name: ghcr.io/kubeflow/kfp-api-server
  newName: docker.io/library/apiserver
  newTag: latest
- name: ghcr.io/kubeflow/kfp-persistence-agent
  newName: docker.io/library/persistenceagent
  newTag: latest
- name: ghcr.io/kubeflow/kfp-scheduled-workflow-controller
  newName: docker.io/library/scheduledworkflow
  newTag: latest
- name: ghcr.io/kubeflow/kfp-driver
  newName: docker.io/library/driver
  newTag: latest
- name: ghcr.io/kubeflow/kfp-launcher
  newName: docker.io/library/launcher
  newTag: latest

patchesStrategicMerge:
- apiserver-env.yaml
