name: KFP Webhook Integration

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/resources/**'
      - '.github/workflows/kfp-webhooks.yml'
      - 'backend/**'

jobs:
  build-images:
    runs-on: ubuntu-latest
    name: Build KFP images
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and upload images
        uses: ./.github/actions/build-images

  webhook-tests:
    runs-on: ubuntu-latest
    needs: [build-images]
    strategy:
      matrix:
        k8s_version: [ "v1.29.2", "v1.30.2", "v1.31.0" ]
    name: KFP Webhooks - K8s ${{ matrix.k8s_version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create KFP cluster
      id: create-kfp-cluster
      uses: ./.github/actions/kfp-cluster
      with:
        k8s_version: ${{ matrix.k8s_version }}
      env:
        PIPELINE_STORE: kubernetes
      continue-on-error: true

    - name: Download and load images
      if: ${{ (steps.create-kfp-cluster.outcome == 'success' )}}
      uses: ./.github/actions/download-images

    - name: Deploy KFP
      if: ${{ (steps.create-kfp-cluster.outcome == 'success' )}}
      uses: ./.github/actions/deploy-kfp
      env:
        PIPELINE_STORE: kubernetes

    - name: Run Webhook Integration Tests
      id: tests
      if: ${{ (steps.create-kfp-cluster.outcome == 'success' )}}
      run: |
        make -C backend/test/integration test-webhook
      continue-on-error: true

    - name: Collect failed logs
      if: ${{ (steps.create-kfp-cluster.outcome != 'success' ) || ( steps.tests.outcome != 'success' )}}
      run: |
        ./.github/resources/scripts/collect-logs.sh --ns kubeflow --output /tmp/tmp_pod_log.txt
        exit 1

    - name: Collect test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: kfp-samples-tests-artifacts-k8s-${{ matrix.k8s_version }}
        path: /tmp/tmp*/*
