name: KFP Webhook Integration

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/resources/**'
      - '.github/workflows/kfp-webhooks.yml'
      - 'backend/**'

jobs:
  webhook-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: [ "v1.29.2", "v1.30.2", "v1.31.0" ]
    name: KFP Webhooks - K8s ${{ matrix.k8s_version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create KFP cluster
      id: create-kfp-cluster
      uses: ./.github/actions/create-cluster
      with:
        k8s_version: ${{ matrix.k8s_version }}
      continue-on-error: true
      
    - name: Build KFP images
      id: build-kfp-images
      if: ${{ steps.create-kfp-cluster.outcome == 'success' }}
      uses: ./.github/actions/build-images
      continue-on-error: true
      
    - name: Deploy KFP
      id: deploy-kfp
      if: ${{ steps.build-kfp-images.outcome == 'success' }}
      uses: ./.github/actions/deploy-kfp
      env:
        PIPELINE_STORE: kubernetes
      continue-on-error: true

    - name: Run Webhook Integration Tests
      id: tests
      if: ${{ steps.deploy-kfp.outcome == 'success' }}
      run: |
        make -C backend/test/integration test-webhook
      continue-on-error: true

    - name: Collect failed logs
      if: ${{ (steps.create-kfp-cluster.outcome != 'success' ) || (steps.build-kfp-images.outcome != 'success' ) || (steps.deploy-kfp.outcome != 'success' ) || ( steps.tests.outcome != 'success' )}}
      run: |
        ./.github/resources/scripts/collect-logs.sh --ns kubeflow --output /tmp/tmp_pod_log.txt
        exit 1

    - name: Collect test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: kfp-samples-tests-artifacts-k8s-${{ matrix.k8s_version }}
        path: /tmp/tmp*/*
